# Generated by Django 3.1 on 2021-01-25 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('station', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('created', models.DateTimeField(editable=False, null=True)),
                ('updated', models.DateTimeField(editable=False, null=True)),
                ('id', models.CharField(editable=False, max_length=64, primary_key=True, serialize=False)),
                ('date', models.DateField(null=True)),
                ('temperature', models.FloatField(null=True)),
                ('temperature_attributes', models.IntegerField(null=True)),
                ('station', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='observation_relation', to='station.station')),
            ],
            options={
                'verbose_name': 'observation',
                'verbose_name_plural': 'observations',
                'db_table': 'noaa_stations_observation',
                'ordering': ['station_id', '-date'],
                'abstract': False,
                'unique_together': {('station_id', 'date')},
            },
        ),
    ]
