# Generated by Django 3.1 on 2021-01-25 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('observation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='observation',
            old_name='temperature',
            new_name='temp',
        ),
        migrations.RenameField(
            model_name='observation',
            old_name='temperature_attributes',
            new_name='temp_attrs',
        ),
    ]
