# Generated by Django 3.1 on 2021-01-22 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('environment', '0002_auto_20190520_0649'),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('created', models.DateTimeField(editable=False, null=True)),
                ('updated', models.DateTimeField(editable=False, null=True)),
                ('id', models.CharField(editable=False, max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(editable=False, max_length=256)),
                ('number', models.CharField(max_length=255)),
                ('lat', models.FloatField(null=True)),
                ('lon', models.FloatField(null=True)),
                ('elevation', models.FloatField(null=True)),
                ('environment', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='station_relation', to='environment.environment')),
            ],
            options={
                'verbose_name': 'station',
                'verbose_name_plural': 'stations',
                'db_table': 'noaa_stations_station',
                'ordering': ['elevation', 'number'],
                'abstract': False,
                'unique_together': {('number', 'name')},
            },
        ),
    ]
